### ISSUE TITLE
Update to nginx 1.11.8

### ISSUE THREAD

**Issue by jggc** [openresty/openresty#223] opened 2017-01-06 22:13 UTC
I'm using the latest docker image https://hub.docker.com/_/kong/ which comes with openresty/1.11.2.1 and does not support latest nginx features, I guess it is simply based on nginx 1.11.2 .

So please update openresty to bundle latest nginx mainline 1.11.8

**Comment by agentzh** [comment] 2017-01-07 08:23
It takes a lot of time and effort to test every new nginx core bundled in OpenResty since incompatibilies and even regressions happen in new nginx cores from time to time. We will work on it soon. BTW, the latest OpenResty formal release is 1.11.2.2 though it still includes the nginx 1.11.2 core.

**Comment by jggc** [comment] 2017-01-07 13:52
This makes sense I was not expecting that to be a one liner. Thanks for the update.

**Comment by danihodovic** [comment] 2017-03-09 10:10
Any time estimate until the next upgrade of nginx core @agentzh ?

We are using nginx `stream { }` block with a resolver like so
```
stream {
  server {
    resolver xxxx;
    listen 1555;
    set $some_addr some_addr;
    proxy_pass $some_addr;
  }
}
```
However this feature is only available in 1.11.3. :disappointed:

**Comment by krish7919** [comment] 2017-04-11 16:44
Is there a timeline for this update?

**Comment by agentzh** [comment] 2017-04-11 18:12
OpenResty 1.11.2.3 RC1 was just out. We will try upgrading the nginx core to the latest version of the 1.11.x series at that time after nginx 1.11.2.3 formal is out. There have been various incompatibilities introduced by latest nginx core releases that must be taken care of properly.

**Comment by agentzh** [comment] 2017-04-25 16:26
We'll try upgrading to the latest NGINX 1.13.x series in the next OpenResty release. 1.11.8 is already not the latest one anyway. I'm closing this.

**Closed by agentzh** 2017-04-25 16:26 UTC

**Comment by krish7919** [comment] 2017-04-25 16:28
@agentzh Any idea how long will it take?

**Comment by agentzh** [comment] 2017-04-25 16:31
@krish7919 All the testing and release engineering work will take at least one month. We take the compatibility issue VERY seriously since we have so many large-scale production users of OpenResty.

**Comment by krish7919** [comment] 2017-04-25 16:32
@agentzh Thanks!

**Comment by ssharma** [comment] 2017-08-24 17:56
@agentzh Openresty is amazing! 👍  We wanted to useout `log_format name escape=json` introduced in nginx `1.11.8`. Any update on nginx core upgrade?

**Comment by agentzh** [comment] 2017-08-24 20:08
@ssharma Next formal OpenResty version will be based on nginx 1.13.4+.

**Comment by ssharma** [comment] 2017-08-24 21:14
@agentzh Thanks for the update!

**Comment by dovreshef** [comment] 2017-10-24 11:51
@agentzh. Thanks for all the hard work! 
Any updates when is the next release due?

**Comment by agentzh** [comment] 2017-10-24 15:17
@dovreshef We're still testing the nginx 1.13.6 core on our side. The new OpenResty RC release 1.13.6.1rc1 should be out in the next couple of weeks. Sorry for the delay on our side. Thanks for the wait!
